GLOBAL:
  TRAIN_DIR: "E:/Datasets/COCO/train2014"
  TRAIN_TXT: "E:/Datasets/COCO/annotations/captions_train2014.json"
  VALID_DIR: "E:/Datasets/COCO/val2014"
  VALID_TXT: "E:/Datasets/COCO/annotations/captions_val2014.json"
  PREPROCESS: "E:/Datasets/COCO/preprocessed"

TRAIN:
  GLR: 0.0001
  DLR: 0.0000001
  BS: 32
  MAX_EPOCH: 300

MODEL:
  ENCODER: "BLSTM"
  GENERATOR: "DFG"
  DISCRIMINATOR: "DFG"
